# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailadmin', '0005_auto_20150125_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgunit',
            name='admin_groups',
            field=models.ManyToManyField(blank=True, related_name='admin_orgunits', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='member_groups',
            field=models.ManyToManyField(blank=True, related_name='member_orgunits', to='auth.Group'),
        ),
    ]
